constants:
  #period_column=self.period_column,
  #  coicop_column=self.coicop_column,
  
  receipt_text_column: "receipt_text"
  product_id_column: "product_id"
  amount_column: "amount"
  revenue_column: "revenue"
  coicop_columns:
    - "coicop_level_1"
    - "coicop_level_2"
    - "coicop_level_3"
    - "coicop_level_4"
    - "coicop_number"

report_settings:
  # Analysis for whole store
  # report_stores:
  #   - ah
  #   - lidl 
  #   - plus 
  #   - jumbo



  texts_per_product_id_histogram: 
      - type: plot
        pivot: false
        output_filename: "{{store_name}}_texts_per_product_id_histogram.png"
        settings: 
            plot_type: bar_chart
            x_column: {{receipt_text_column}}
            y_column: count
            title: Unique receipt texts per product_id for {{store_name}}
      - type: table
        pivot: false
        output_filename: "{{store_name}}_texts_per_product_id_histogram.md"
        settings:
            table_type: markdown 
  log_texts_per_product_id_histogram: 
      - type: plot
        pivot: false
        output_filename: "{{store_name}}_log_texts_per_product_id_histogram.png"
        settings: 
            plot_type: bar_chart
            x_column: {{receipt_text_column}}
            y_column: count
            title: Unique receipt texts per product_id for {{store_name}} (Log scale)
  receipt_length_histogram: 
      - type: plot
        pivot: false
        output_filename: "{{store_name}}_receipt_length_histogram.png"
        settings: 
            plot_type: bar_chart
            x_column: {{receipt_text_column}}
            y_column: count
            title: Receipt text length histogram for {{store_name}}
  product_id_length_histogram: 
      - type: plot
        pivot: false
        output_filename: "{{store_name}}_product_id_length_histogram.png"
        settings: 
            plot_type: bar_chart
            x_column: {{product_id_column}}
            y_column: count
            title: product_id length histogram for {{store_name}}
  revenue_for_coicop_hierarchy: 
    - type: plot
      pivot: false
      output_filename: "{{store_name}}_revenue_for_coicop_hierarchy_sunburst.html"
      settings: 
          plot_type: sunburst_chart
          format: html
          sunburst_columns: {{coicop_columns}}
          amount_column: {{revenue_column}}
          title: Sunburst of revenue per coicop level for {{store_name}}
  
  product_revenue_versus_lifetime:
    - type: plot  
      pivot: false
      output_filename: "{{store_name}}_{{period_column}}_product_revenue_versus_lifetime.png"
      settings: 
          plot_type: scatter_plot
          x_column: {{period_column}}
          y_column: {{revenue_column}}
          title: Product revenue versus lifetime for {{store_name}}
    - type: plot  
      pivot: false
      output_filename: "{{store_name}}_{{period_column}}_product_amount_versus_lifetime.png"
      settings: 
          plot_type: scatter_plot
          x_column: {{period_column}}
          y_column: {{amount_column}}
          title: Product amount versus lifetime for {{store_name}}
  
  # Analysis per COICOP

  unique_coicop_values_per_coicop: 
    - type: plot  
      pivot: true
      value_columns: 
        - {{product_id_column}}
        - {{receipt_text_column}}
      output_filename: "{{store_name}}_{{coicop_column}}_unique_receipt_values_per_coicop.png"
      settings: 
          plot_type: bar_chart
          x_column: {{coicop_column}}
          y_column: value
          group_column: group
          title: Unique receipt texts per {{coicop_column}} for {{store_name}}

  # Analysis per period
  
  unique_column_values_per_period: 
    - type: plot  
      pivot: true
      value_columns: 
        - {{product_id_column}} 
        - {{receipt_text_column}}
      output_filename: "{{store_name}}_{{period_column}}_unique_receipt_values_per_period_column.png"
      settings: 
          plot_type: line_chart
          x_column: {{period_column}}
          y_column: value
          group_column: group
          title: Unique receipt texts per {{period_column}} for {{store_name}}
  total_revenue_per_period: 
    - type: plot  
      pivot: false
      output_filename: "{{store_name}}_{{period_column}}_total_revenue_per_period.png"
      settings: 
          plot_type: line_chart
          x_column: {{period_column}}
          y_column: {{revenue_column}}
          title: Total revenue per {{period_column}} for {{store_name}}
    - type: plot  
      pivot: false
      output_filename: "{{store_name}}_{{period_column}}_total_amount_per_period.png"
      settings: 
          plot_type: line_chart
          x_column: {{period_column}}
          y_column: {{amount_column}}
          title: Total amount per {{period_column}} for {{store_name}}
  compare_products_per_period: 
    - type: plot  
      pivot: true
      value_columns: 
        - number_{{receipt_text_column}}_introduced
        - number_{{receipt_text_column}}_removed
        - number_{{product_id_column}}_introduced
        - number_{{product_id_column}}_removed
      output_filename: "{{store_name}}_{{period_column}}_{{coicop_column}}_compare_products_per_period.png"
      settings: 
          plot_type: line_chart
          x_column: {{period_column}}
          y_column: value
          group_column: group
          title: Number of products introduced/removed per {{period_column}} for {{store_name}}
    - type: plot
      pivot: false 
      value_columns:
        - {{period_column}}
        - jaccard_index_{{receipt_text_column}}_{{period_column}}
      output_filename: "overlap_{{store_name}}_{{period_column}}_jaccard_index_{{receipt_text_column}}.png"
      settings:
          plot_type: line_chart
          x_column: {{period_column}}
          y_column: jaccard_index_{{receipt_text_column}}_{{period_column}}
          title: Jaccard index of {{receipt_text_column}} overlap per {{period_column}} for {{store_name}}
    - type: plot
      pivot: false 
      value_columns:
        - {{period_column}}
        - jaccard_index_{{product_id_column}}_{{period_column}}
      output_filename: "overlap_{{store_name}}_{{period_column}}_jaccard_index_{{product_id_column}}.png"
      settings:
          plot_type: line_chart
          x_column: {{period_column}}
          y_column: jaccard_index_{{product_id_column}}_{{period_column}}
          title: Jaccard index of {{product_id_column}} overlap per {{period_column}} for {{store_name}}      
    - type: plot
      pivot: false 
      sort_values:
        columns:
          - {{period_column}}
        ascending: true
      value_columns:
        - {{period_column}}
        - total_{{product_id_column}}
      output_filename: "{{store_name}}_{{period_column}}_total_number_{{product_id_column}}.png"
      settings:
          plot_type: bar_chart
          x_column: {{period_column}}
          y_column: total_{{product_id_column}}
          title: Bar chart of the total number of {{product_id_column}} per {{period_column}} for {{store_name}}  
  product_availability_in_period:  
    - type: plot
      pivot: false 
      sort_values:
        columns:
          - {{product_id_column}}
        ascending: true
      value_columns:
        - {{product_id_column}}
      output_filename: "{{store_name}}_{{period_column}}_{{product_id_column}}_availability.png"
      settings:
          plot_type: heatmap
          title: Heatmap of {{product_id_column}} availability for {{store_name}}  
    - type: plot
      pivot: false 
      output_filename: "{{store_name}}_{{period_column}}_{{receipt_text_column}}_availability.png"
      settings:
          plot_type: heatmap
          title: Heatmap of {{receipt_text_column}} availability for {{store_name}} 
  product_lifetime_in_periods:
    - type: plot
      pivot: false 
      sort_values:
        columns:
          - {{product_id_column}}
          - {{period_column}}
        ascending: true
      value_columns:
        - {{product_id_column}}
      output_filename: "{{store_name}}_{{period_column}}_{{product_id_column}}_lifetime.png"
      settings:
          plot_type: histogram
          x_column: {{period_column}}
          title: Histogram of {{product_id_column}} lifetime for {{store_name}}  

  # Analysis per period and coicop
  total_revenue_per_coicop_and_period:
    - type: plot 
      pivot: false
      sort_values:
        columns:
          - {{period_column}}
          - {{coicop_column}}          
        ascending: true 
      value_columns:
        - {{period_column}}
        - {{coicop_column}}
        - {{revenue_column}}
      output_filename: "{{store_name}}_{{period_column}}_{{coicop_column}}_total_revenue_{{product_id_column}}.png"
      settings:
          plot_type: bar_chart
          x_column: {{period_column}}
          y_column: {{revenue_column}}
          group_column: {{coicop_column}}
          title: Bar chart of the total revenue per {{coicop_column}} and {{period_column}} for {{store_name}} 
    - type: plot 
      pivot: false
      sort_values:
        columns:
          - {{period_column}}
          - {{coicop_column}}          
        ascending: true 
      value_columns:
        - {{period_column}}
        - {{coicop_column}}
        - {{amount_column}}
      output_filename: "{{store_name}}_{{period_column}}_{{coicop_column}}_total_amount_{{product_id_column}}.png"
      settings:
          plot_type: bar_chart
          x_column: {{period_column}}
          y_column: {{amount_column}}
          group_column: {{coicop_column}}
          title: Bar chart of the total amount of products sold per {{coicop_column}} and {{period_column}} for {{store_name}}       

  compare_products_per_period_coicop_level:
    - type: plot
      pivot: false 
      sort_values:
        columns:
          - {{period_column}}
          - {{coicop_column}}
        ascending: true
      value_columns:
        - {{period_column}}
        - {{coicop_column}}
        - total_{{product_id_column}}
      output_filename: "{{store_name}}_{{period_column}}_{{coicop_column}}_total_number_{{product_id_column}}.png"
      settings:
          plot_type: bar_chart
          x_column: {{period_column}}
          y_column: total_{{product_id_column}}
          group_column: {{coicop_column}}
          title: Bar chart of the total number of {{product_id_column}} per {{period_column}} for {{store_name}} 